import { SectorConfig } from '@/types';

export const SECTOR_CONFIGS: Record<string, SectorConfig> = {
  tailor: {
    id: 'tailor',
    label: 'Terzi Paneli',
    icon: '✂️',
    color: '#8B5CF6',
    gradient: 'from-violet-600 to-purple-700',
    description: 'Sipariş, ölçü ve teslim takibi',
    orderFields: [
      { key: 'chest', label: 'Göğüs (cm)', type: 'number' },
      { key: 'waist', label: 'Bel (cm)', type: 'number' },
      { key: 'hip', label: 'Kalça (cm)', type: 'number' },
      { key: 'shoulder', label: 'Omuz (cm)', type: 'number' },
      { key: 'length', label: 'Boy (cm)', type: 'number' },
      { key: 'fabric_type', label: 'Kumaş Türü', type: 'select', options: ['Yün', 'Pamuk', 'Keten', 'İpek', 'Polyester', 'Denim', 'Diğer'] },
      { key: 'color', label: 'Renk / Desen', type: 'text' },
      { key: 'trial_date', label: 'Prova Tarihi', type: 'date' },
      { key: 'product_type', label: 'Ürün Türü', type: 'select', options: ['Takım Elbise', 'Gömlek', 'Pantolon', 'Etek', 'Elbise', 'Palto', 'Diğer'] },
      { key: 'notes', label: 'Özel Notlar', type: 'textarea' },
    ],
    features: ['Ölçü Kayıtları', 'Prova Takvimi', 'Sipariş Takibi', 'Teslimat Yönetimi', 'Kumaş Stoku'],
    dashboardWidgets: ['bugunku_teslimatlar', 'provalar', 'gec_kalan_isler', 'aylik_gelir'],
  },
  furniture: {
    id: 'furniture',
    label: 'Mobilya Paneli',
    icon: '🪑',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-orange-600',
    description: 'Üretim, montaj ve teslim yönetimi',
    orderFields: [
      { key: 'width', label: 'Genişlik (cm)', type: 'number' },
      { key: 'height', label: 'Yükseklik (cm)', type: 'number' },
      { key: 'depth', label: 'Derinlik (cm)', type: 'number' },
      { key: 'material', label: 'Malzeme', type: 'select', options: ['MDF', 'Masif', 'Sunta', 'Metal', 'Cam', 'Mermer', 'Diğer'] },
      { key: 'color', label: 'Renk / Kaplama', type: 'text' },
      { key: 'product_type', label: 'Ürün Türü', type: 'select', options: ['Koltuk', 'Kanepe', 'Yatak', 'Yemek Masası', 'Çalışma Masası', 'Dolap', 'Raf', 'TV Ünitesi', 'Diğer'] },
      { key: 'assembly_date', label: 'Montaj Tarihi', type: 'date' },
      { key: 'assembly_address', label: 'Montaj Adresi', type: 'text' },
      { key: 'production_stage', label: 'Üretim Aşaması', type: 'select', options: ['Kesim', 'Birleştirme', 'Boyama', 'Döşeme', 'Paketleme', 'Hazır'] },
      { key: 'notes', label: 'Özel Notlar', type: 'textarea' },
    ],
    features: ['Üretim Takibi', 'Montaj Takvimi', 'Malzeme Yönetimi', 'Depo Takibi', 'Teslimat Planı'],
    dashboardWidgets: ['uretimde_isler', 'montaj_takvimi', 'kapora_bekleyenler', 'aylik_gelir'],
  },
  dental: {
    id: 'dental',
    label: 'Klinik Paneli',
    icon: '🦷',
    color: '#10B981',
    gradient: 'from-emerald-500 to-teal-600',
    description: 'Hasta, randevu ve tedavi yönetimi',
    orderFields: [
      { key: 'treatment_type', label: 'Tedavi Türü', type: 'select', options: ['Diş Çekimi', 'Dolgu', 'Kanal Tedavisi', 'İmplant', 'Protez', 'Ortodonti', 'Beyazlatma', 'Diş Eti Tedavisi', 'Diğer'] },
      { key: 'tooth_number', label: 'Diş No', type: 'text' },
      { key: 'diagnosis', label: 'Teşhis', type: 'textarea' },
      { key: 'treatment_plan', label: 'Tedavi Planı', type: 'textarea' },
      { key: 'session_count', label: 'Seans Sayısı', type: 'number' },
      { key: 'completed_sessions', label: 'Tamamlanan Seans', type: 'number' },
      { key: 'next_appointment', label: 'Sonraki Randevu', type: 'date' },
      { key: 'anesthesia', label: 'Anestezi', type: 'select', options: ['Lokal', 'Genel', 'Sedation', 'Yok'] },
      { key: 'allergies', label: 'Alerji / Özel Durum', type: 'textarea' },
      { key: 'xray_notes', label: 'Röntgen Notları', type: 'textarea' },
    ],
    features: ['Hasta Kaydı', 'Randevu Sistemi', 'Tedavi Planı', 'Ödeme Planı', 'Hasta Takibi'],
    dashboardWidgets: ['bugunun_randevulari', 'yeni_hastalar', 'tedavi_surecleri', 'tahsilatlar'],
  },
  printing: {
    id: 'printing',
    label: 'Matbaa Paneli',
    icon: '🖨️',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-indigo-600',
    description: 'Baskı siparişi ve teslimat yönetimi',
    orderFields: [
      { key: 'product_type', label: 'Ürün Türü', type: 'select', options: ['Kartvizit', 'Broşür', 'Katalog', 'Afiş', 'Branda', 'Sticker', 'Ambalaj', 'Kitap', 'Diğer'] },
      { key: 'quantity', label: 'Adet', type: 'number' },
      { key: 'size', label: 'Boyut', type: 'text' },
      { key: 'paper_type', label: 'Kağıt / Malzeme', type: 'select', options: ['Kuşe 90gr', 'Kuşe 135gr', 'Kuşe 170gr', 'Bristol', 'Kraft', 'Branda', 'Vinyl', 'Diğer'] },
      { key: 'print_type', label: 'Baskı Türü', type: 'select', options: ['Tek Yüz', 'Çift Yüz', 'Tek Renk', 'CMYK', 'Pantone'] },
      { key: 'lamination', label: 'Laminasyon', type: 'select', options: ['Yok', 'Parlak', 'Mat', 'Soft Touch', 'UV Selektif'] },
      { key: 'cutting', label: 'Kesim', type: 'select', options: ['Düz', 'Yuvarlak Köşe', 'Özel Şekil'] },
      { key: 'design_ready', label: 'Tasarım Hazır mı?', type: 'select', options: ['Evet', 'Hayır - Biz Yapacağız', 'Revizyon Gerekli'] },
      { key: 'delivery_method', label: 'Teslimat', type: 'select', options: ['Elden Teslim', 'Kargo', 'Kurye'] },
      { key: 'notes', label: 'Özel Notlar', type: 'textarea' },
    ],
    features: ['Sipariş Takibi', 'Tasarım Onay', 'Baskı Kuyruğu', 'Teslimat Yönetimi', 'Fiyat Hesaplama'],
    dashboardWidgets: ['bekleyen_isler', 'baski_kuyrugu', 'teslim_edilecekler', 'aylik_gelir'],
  },
  autoservice: {
    id: 'autoservice',
    label: 'Oto Servis Paneli',
    icon: '🔧',
    color: '#EF4444',
    gradient: 'from-red-500 to-rose-600',
    description: 'Araç bakım ve servis yönetimi',
    orderFields: [
      { key: 'plate', label: 'Plaka', type: 'text', required: true },
      { key: 'brand', label: 'Marka', type: 'select', options: ['BMW', 'Mercedes', 'Audi', 'Volkswagen', 'Toyota', 'Ford', 'Renault', 'Fiat', 'Opel', 'Honda', 'Hyundai', 'Diğer'] },
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'year', label: 'Yıl', type: 'number' },
      { key: 'km', label: 'Kilometre', type: 'number' },
      { key: 'service_type', label: 'Servis Türü', type: 'select', options: ['Periyodik Bakım', 'Motor', 'Fren', 'Şanzıman', 'Elektrik', 'Kaporta', 'Boya', 'Lastik', 'Egzoz', 'Diğer'] },
      { key: 'complaint', label: 'Arıza / Şikayet', type: 'textarea' },
      { key: 'diagnosis', label: 'Teşhis', type: 'textarea' },
      { key: 'parts_used', label: 'Kullanılan Parçalar', type: 'textarea' },
      { key: 'technician', label: 'Teknisyen', type: 'text' },
    ],
    features: ['Araç Kaydı', 'Servis Takibi', 'Parça Yönetimi', 'Randevu Sistemi', 'Müşteri Geçmişi'],
    dashboardWidgets: ['servisteki_araclar', 'bugunun_randevulari', 'teslim_edilecekler', 'aylik_gelir'],
  },
};

export const getSectorConfig = (sector: string): SectorConfig => {
  return SECTOR_CONFIGS[sector] || SECTOR_CONFIGS['tailor'];
};

export const SECTOR_ORDER_STATUS_LABELS: Record<string, Record<string, string>> = {
  tailor: {
    pending: 'Beklemede',
    in_progress: 'Dikimde',
    waiting_approval: 'Prova Bekliyor',
    ready: 'Teslime Hazır',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal',
  },
  furniture: {
    pending: 'Beklemede',
    in_progress: 'Üretimde',
    waiting_approval: 'Onay Bekliyor',
    ready: 'Teslime Hazır',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal',
  },
  dental: {
    pending: 'Beklemede',
    in_progress: 'Tedavi Devam Ediyor',
    waiting_approval: 'Onay Bekliyor',
    ready: 'Tamamlandı',
    delivered: 'Kapatıldı',
    cancelled: 'İptal',
  },
  printing: {
    pending: 'Sipariş Alındı',
    in_progress: 'Baskıda',
    waiting_approval: 'Tasarım Onayı',
    ready: 'Teslime Hazır',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal',
  },
  autoservice: {
    pending: 'Kabul Edildi',
    in_progress: 'Serviste',
    waiting_approval: 'Parça Bekliyor',
    ready: 'Teslime Hazır',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal',
  },
};

export const getStatusLabel = (sector: string, status: string): string => {
  return SECTOR_ORDER_STATUS_LABELS[sector]?.[status] || status;
};

export const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  in_progress: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  waiting_approval: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  ready: 'bg-green-500/20 text-green-400 border-green-500/30',
  delivered: 'bg-gray-500/20 text-gray-400 border-gray-500/30',
  cancelled: 'bg-red-500/20 text-red-400 border-red-500/30',
};
